# Generated by Django 5.2.2 on 2025-06-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('number_plate', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('bodaboda', 'Bodaboda Rider'), ('pickup', 'Pickup Driver'), ('lorry', 'Lorry Driver')], max_length=10)),
                ('sacco', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(default='default_driver.png', upload_to='drivers/')),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorbike.driver')),
            ],
        ),
    ]
