# Generated by Django 5.2.2 on 2025-06-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('motorbike', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_available',
        ),
        migrations.AddField(
            model_name='driver',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='driver_set', related_query_name='driver', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='driver_set', related_query_name='driver', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='number_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_driver.png', null=True, upload_to='drivers/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='role',
            field=models.CharField(blank=True, choices=[('bodaboda', 'Bodaboda Rider'), ('pickup', 'Pickup Driver'), ('lorry', 'Lorry Driver')], max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='sacco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='stage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
