# Generated by Django 5.2.2 on 2025-06-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike', '0002_remove_driver_is_available_driver_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
