# Generated by Django 5.2.2 on 2025-06-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike', '0003_alter_driver_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
