# Generated by Django 5.2.2 on 2025-06-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike', '0004_alter_driver_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AlterField(
            model_name='driver',
            name='role',
            field=models.CharField(blank=True, choices=[('bodaboda', 'Boda Boda'), ('pickup', 'Pickup'), ('lorry', 'Lorry')], max_length=50),
        ),
    ]
