# Generated by Django 5.2.2 on 2025-06-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('motorbike', '0005_driver_is_available_driver_photo_driver_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='driver_set', related_query_name='driver', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='driver_set', related_query_name='driver', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
